# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'environment'
        # Default value if no value is explicitly provided
        default: 'DEV'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Run environment type ${{ inputs.name }}"


    - name: Build frontEnd
      id: build-frontend
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |

        cd ./src/frontend
        docker build -t frontend:$IMAGE_TAG .
        echo "image=frontend:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build backend
      id: build-backend
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |

         cd ./src/backend
         docker build -t backend:$IMAGE_TAG .
         echo "image=backend:$IMAGE_TAG" >> $GITHUB_OUTPUT

#    - name: Upload frontend to enable deployment
#      uses: actions/upload-artifact@v3
#      with:
#          name: poduction file
#          path: ./todo/build

#    - name: Upload backend to enable deployment
#      uses: actions/upload-artifact@v3
#      with:
#          name: poduction file
#          path: ./todo/build
